### ISSUE TITLE
The link to original code and data is invalid

### ISSUE THREAD

**Issue by ProQianXiao** [gdario/deep_ppi#2]
Hi,
Thanks for your effort providing the update for  keras 2.0. I have read the paper and want to have a look at the code and datasets used in the paper, but  unfortunately, the link is invalid now.
Could you share the original code and datasets if possible? 
Thanks very much!

**Comment by gdario** [comment]
Hi, thanks for contacting me. I must admit I haven't checked this code or the data in quite a long time. You are indeed right that the link in the README is no longer valid. This one is the same link the authors included in the paper. I suppose the best bet would be to contact the authors directly, as they may have moved the repository to a different location. I'm afraid there's not much else I can do. Sorry!

**Comment by ProQianXiao** [comment]
Fine, thanks for your quick response.  I will try to contact the authors directly. Still thank you for your help.
